#
# Licensed to Cloudkick, Inc ('Cloudkick') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Cloudkick licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import os

from os.path import join as pjoin

ignored_paths = ['extern/']

cwd = os.getcwd()

def is_valid_path(path, is_file = False):
  for ignored_path in ignored_paths:
    if path.startswith(ignored_path) or (is_file and not path.endswith('.js')):
      return False

  return True

source = []
for (dirpath, dirnames, filenames) in os.walk(cwd):
  dirname = dirpath.replace(cwd + '/', '') + '/'

  if not is_valid_path(dirname):
    continue

  for filename in filenames:
    file_path = pjoin(dirname, filename)

    if is_valid_path(file_path, True):
      source.append(File(file_path))

Return("source")
