#
# Licensed to Cloudkick, Inc ('Cloudkick') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Cloudkick licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

from os.path import join as pjoin

src = {
        'util':
            [ 'config.js',
              'fs.js',
              'command_parser.js',
              'http.js',
              'http_pumpfile.js',
              'log.js',
              'misc.js',
              'pubsub.js',
              'ringbuf.js',
              'version.js',
              'tail.js',
              'tarball.js',
              'templates.js',
              'terminal.js'],
        'cast-agent':
            [ 'entry.js'],
        'cast-client':
            [ 'entry.js',
              'commands/version.js',
              'commands/bundles/create.js',
              'commands/bundles/upload.js',
              'commands/services/tail.js',
              'commands/remotes/add.js'],
        'health':
            ['index.js',
             'checks/http.js',
             'checks/tcp.js'],
        'norris':
            ['index.js'],
        'norris/facts':
            ['arch.js',
             'gnutar.js',
             'hostname.js',
             'kernel.js'],
        'runit':
            [ 'services.js'],
        'services':
            [ 'http.js',
              'runit.js'],
        'services/http':
            [ 'bundles.js',
              'services.js',
              'test.js'],
}

source = []
for k in src.keys():
  for p in src[k]:
    source.append(File(pjoin(k, p)))

Return("source")
