#
# Licensed to Cloudkick, Inc ('Cloudkick') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# Cloudkick licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

from os.path import join as pjoin

utilssrc = ['config.js',
            'log.js',
            'pubsub.js',
            'version.js']

agentsrc = ['entry.js']

clientsrc = ['entry.js']

src = [ ]

src.extend([pjoin('util', i) for i in utilssrc])
src.extend([pjoin('cast-agent', i) for i in agentsrc])
src.extend([pjoin('cast-client', i) for i in clientsrc])

source = [File(x) for x in src]

Return("source")
